/*
 * This file is generated by jOOQ.
 */
package art.aelaort;


import art.aelaort.tables.Quotes;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index QUOTES_GIN_TRGM_IDX = Internal.createIndex(DSL.name("quotes_gin_trgm_idx"), Quotes.QUOTES, new OrderField[] { Quotes.QUOTES.QUOTE }, false);
}
