/*
 * This file is generated by jOOQ.
 */
package art.aelaort;


import art.aelaort.tables.Quotes;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.quotes</code>.
     */
    public static final Quotes QUOTES = Quotes.QUOTES;
}
